version: "3"

services:
  postgres:
    image: postgres:9.6.2
    ports:
      - ${PORTS__POSTGRES:-5432}:5432
    environment:
      - POSTGRES_USER=${POSTGRES__USER:-api}
      - POSTGRES_PASSWORD=${POSTGRES__PASS:-3x4mpl3}
      - POSTGRES_DB=${POSTGRES__DB:-gymbror}
      - POSTGRES_INITDB_ARGS=--encoding=utf8
